version: '3'

volumes:
  db-data:
    driver: local


services:
  db:
    image: postgres:15.1-alpine
    container_name: postgesql
    ports:
      - '5439:5432'
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data