spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5439/${POSTGRES_DATABASE}
    username: ${PG_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true
    default-schema: public
  data:
    rest:
      base-path: /api